### ISSUE TITLE
Context menu bug

### ISSUE THREAD

**Issue by Kristinita** [borysf/Sublimerge#1]
### Summary

An error occurs when I open the context menu.

### Steps to reproduce

I checked on plain Sublime Text Portable without plugins. I clicked the right mouse button anywhere in the text and get it:

```
Traceback (most recent call last):
  File "E:\Sublime Text 3 Portable For Tests\sublime_plugin.py", line 511, in description_
    return self.description(**args)
  File "/Users/borys/Library/Application Support/Sublime Text 3/Packages/Sublimerge 3/commands/commands_diff.py", line 159, in description
AttributeError: 'bool' object has no attribute 'is_2way'
Traceback (most recent call last):
  File "E:\Sublime Text 3 Portable For Tests\sublime_plugin.py", line 511, in description_
    return self.description(**args)
  File "/Users/borys/Library/Application Support/Sublime Text 3/Packages/Sublimerge 3/commands/commands_diff.py", line 159, in description
AttributeError: 'bool' object has no attribute 'is_2way'
Traceback (most recent call last):
  File "E:\Sublime Text 3 Portable For Tests\sublime_plugin.py", line 511, in description_
    return self.description(**args)
  File "/Users/borys/Library/Application Support/Sublime Text 3/Packages/Sublimerge 3/commands/commands_diff.py", line 159, in description
AttributeError: 'bool' object has no attribute 'is_2way'
Traceback (most recent call last):
  File "E:\Sublime Text 3 Portable For Tests\sublime_plugin.py", line 511, in description_
    return self.description(**args)
  File "/Users/borys/Library/Application Support/Sublime Text 3/Packages/Sublimerge 3/commands/commands_diff.py", line 159, in description
AttributeError: 'bool' object has no attribute 'is_2way'
Traceback (most recent call last):
  File "E:\Sublime Text 3 Portable For Tests\sublime_plugin.py", line 511, in description_
    return self.description(**args)
  File "/Users/borys/Library/Application Support/Sublime Text 3/Packages/Sublimerge 3/commands/commands_diff.py", line 159, in description
AttributeError: 'bool' object has no attribute 'is_2way'
Traceback (most recent call last):
  File "E:\Sublime Text 3 Portable For Tests\sublime_plugin.py", line 511, in description_
    return self.description(**args)
  File "/Users/borys/Library/Application Support/Sublime Text 3/Packages/Sublimerge 3/commands/commands_diff.py", line 159, in description
AttributeError: 'bool' object has no attribute 'is_2way'
Traceback (most recent call last):
  File "E:\Sublime Text 3 Portable For Tests\sublime_plugin.py", line 511, in description_
    return self.description(**args)
  File "/Users/borys/Library/Application Support/Sublime Text 3/Packages/Sublimerge 3/commands/commands_diff.py", line 159, in description
AttributeError: 'bool' object has no attribute 'is_2way'
Traceback (most recent call last):
  File "E:\Sublime Text 3 Portable For Tests\sublime_plugin.py", line 511, in description_
    return self.description(**args)
  File "/Users/borys/Library/Application Support/Sublime Text 3/Packages/Sublimerge 3/commands/commands_diff.py", line 159, in description
AttributeError: 'bool' object has no attribute 'is_2way'
```

### Environment

* Operating system and version:  
        [√] Windows 10 Education
  * [ ] Mac OS ...
  * [ ] Linux ...
* Sublime Text:
  * Build 3114
* Sublimerge:
  * Sublimerge 3 established on Sublimerge Pro

**Comment by borysf** [comment]
Fix for this issue will be released with the next update to 3.0.10
